backend:
  name: git-gateway
  branch: main

media_folder: "static/img"       # Where uploaded images are stored
public_folder: "/img"            # How those images are referenced in frontend

site_url: "https://insurance.bramel.co"
logo_url: "/img/logo.svg"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Body", name: "body", widget: "markdown" }
